import test from"node:test";import assert from"node:assert/strict";import{openMarketDatabase}from"../storage/database.js";import{persistRawPage,startCollectorRun,startOperationRun}from"../storage/raw-persistence.js";import{bidEnrichmentIdentity,normalizeBidEnrichmentRawItem}from"./bid-enrichment.js";
const cases=[
 ["getBidPblancListInfoLicenseLimit","bid_license_limit",{lmtGrpNo:"1",lmtSno:"2",lcnsLmtNm:"면허",permIndstrytyList:"업종"}],
 ["getBidPblancListInfoPrtcptPsblRgn","bid_participation_region",{lmtSno:1,prtcptPsblRgnNm:"서울"}],
 ["getBidPblancListInfoChgHstryThng","bid_notice_change_event",{bidClsfcNo:"1",rbidNo:"000",chgItemNm:"공고명",bfchgVal:"전",afchgVal:"후",chgDt:"20260826"}],
 ["getBidPblancListInfoEorderAtchFileInfo","bid_eorder_attachment",{atchFileSno:"1",eorderDocDivNm:"제안서",eorderAtchFileNm:"a.hwp",eorderAtchFileUrl:"https://example.test/a"}],
]as const;
function ingest(db:ReturnType<typeof openMarketDatabase>,operation:string,item:Record<string,unknown>,suffix:string){const at="2026-08-26T00:00:00.000Z",run=startCollectorRun(db,{runId:`r${suffix}`,mode:"verification",startedAt:at,appVersion:"t",parserVersion:"t"}),op=startOperationRun(db,{operationRunId:`o${suffix}`,runId:run,service:"BidPublicInfoService",operation,queryBasis:"test",startedAt:at}),json={response:{header:{resultCode:"00",resultMsg:"OK"},body:{items:[item],pageNo:1,numOfRows:100,totalCount:1}}},body=JSON.stringify(json),saved=persistRawPage(db,{operationRunId:op,service:"BidPublicInfoService",operation,requestedAt:at,completedAt:at,durationMs:1,httpStatus:200,resultCode:"00",resultMsg:"OK",pageNo:1,numOfRows:100,totalCount:1,requestMetadata:{},requestUrl:"https://example.test",responseBytes:new TextEncoder().encode(body),parsedJson:json,parserVersion:"t"});normalizeBidEnrichmentRawItem(db,saved.rawItemIds[0]!,operation,at);normalizeBidEnrichmentRawItem(db,saved.rawItemIds[0]!,operation,at);}
test("all bid enrichment shapes normalize idempotently",()=>{const db=openMarketDatabase(":memory:");for(const [operation,table,item]of cases)ingest(db,operation,{bidNtceNo:"B1",bidNtceOrd:"000",...item},table);for(const[,table]of cases)assert.equal((db.prepare(`SELECT count(*) n FROM ${table}`).get()as{n:number}).n,1);assert.equal((db.prepare("SELECT participation_region_name FROM bid_participation_region").get()as{participation_region_name:string}).participation_region_name,"서울");db.close();});
test("two-part identity keeps notice order distinct and rejects empty required values",()=>{assert.notDeepEqual(bidEnrichmentIdentity({bidNtceNo:"B",bidNtceOrd:"000"}),bidEnrichmentIdentity({bidNtceNo:"B",bidNtceOrd:"001"}));assert.throws(()=>bidEnrichmentIdentity({bidNtceNo:"B",bidNtceOrd:""}),/missing bidNtceOrd/u);});
