import type { DatabaseSync } from "node:sqlite";
import { CONTRACT_OPERATION, CONTRACT_SERVICE, normalizeContract } from "./contract.js";
import { upsertContractItem } from "./contract-source-derived.js";

export type ContractWriteAction="inserted"|"updated"|"unchanged";
export function normalizeEvidenceBackedContractResults(db:DatabaseSync,rawId:number,headerId:number,collectionTargetCodes:readonly string[],at:string):{target:string;action:ContractWriteAction;contractResultId:number}[]{
 const targets=new Set(collectionTargetCodes);if([...targets].some(target=>!/^\d{8}$/.test(target)))throw new Error("INVALID_CONTRACT_TARGET");
 const evidence=db.prepare("SELECT DISTINCT product_class_no target FROM contract_item WHERE contract_header_id=? AND product_class_no IS NOT NULL ORDER BY product_class_no").all(headerId)as{target:string}[];
 return evidence.filter(({target})=>targets.has(target)).map(({target})=>({target,...normalizeContractRawItem(db,rawId,target,at)}));
}
export function normalizeContractRawItem(db:DatabaseSync,rawId:number,target:string,at:string):{action:ContractWriteAction;contractResultId:number}{
 if(!/^\d{8}$/.test(target))throw new Error("INVALID_CONTRACT_TARGET");const row=db.prepare("SELECT service,operation,canonical_json FROM api_raw_item WHERE raw_item_id=?").get(rawId)as{service:string;operation:string;canonical_json:string}|undefined;if(!row||row.service!==CONTRACT_SERVICE||row.operation!==CONTRACT_OPERATION)throw new Error("RAW item is not from the supported contract operation");const n=normalizeContract(JSON.parse(row.canonical_json)as Record<string,unknown>),c=n.candidate,warnings=JSON.stringify(n.warnings),values=[c.contractNo,c.contractName,c.contractMethodName,c.contractInstitutionName,c.demandInstitutionName,c.contractAmount,c.contractDate,c.contractDetailUrl];
 db.exec("BEGIN IMMEDIATE");try{const old=db.prepare("SELECT contract_result_id,semantic_row_hash FROM contract_result WHERE decision_contract_no=?").get(c.decisionContractNo)as{contract_result_id:number;semantic_row_hash:string}|undefined;if(!old){const result=db.prepare("INSERT INTO contract_result(target_detailed_product_class_no,decision_contract_no,contract_no,contract_name,contract_method_name,contract_institution_name,demand_institution_name,contract_amount,contract_date,contract_detail_url,source_raw_item_id,source_operation,semantic_row_hash,semantic_state_json,parse_warnings_json,first_normalized_at,last_normalized_at)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(target,c.decisionContractNo,...values,rawId,CONTRACT_OPERATION,n.semanticRowHash,n.semanticStateJson,warnings,at,at);db.exec("COMMIT");return{action:"inserted",contractResultId:Number(result.lastInsertRowid)};}const action=old.semantic_row_hash===n.semanticRowHash?"unchanged":"updated";db.prepare("UPDATE contract_result SET target_detailed_product_class_no=?,contract_no=?,contract_name=?,contract_method_name=?,contract_institution_name=?,demand_institution_name=?,contract_amount=?,contract_date=?,contract_detail_url=?,source_raw_item_id=?,semantic_row_hash=?,semantic_state_json=?,parse_warnings_json=?,last_normalized_at=? WHERE contract_result_id=?").run(target,...values,rawId,n.semanticRowHash,n.semanticStateJson,warnings,at,old.contract_result_id);db.exec("COMMIT");return{action,contractResultId:old.contract_result_id};}catch(error){db.exec("ROLLBACK");throw error;}
}
export function renormalizeStoredContractDetails(db:DatabaseSync,at:string,targets:readonly string[]=[]):{items:number;results:number}{const items=db.prepare("SELECT contract_header_id headerId,source_raw_item_id rawId FROM contract_item ORDER BY contract_item_id").all()as{headerId:number;rawId:number}[];for(const item of items)upsertContractItem(db,item.headerId,item.rawId,targets,at);const headers=db.prepare("SELECT contract_header_id headerId,source_raw_item_id rawId FROM contract_header ORDER BY contract_header_id").all()as{headerId:number;rawId:number}[];let results=0;for(const header of headers)results+=normalizeEvidenceBackedContractResults(db,header.rawId,header.headerId,targets,at).length;return{items:items.length,results};}
