import type { DatabaseSync } from "node:sqlite";

export const LIFECYCLE_SERVICE="CntrctProcssIntgOpenService",LIFECYCLE_OPERATION="getCntrctProcssIntgOpenThng";
type Obj=Record<string,unknown>;
const obj=(v:unknown):Obj|undefined=>v!==null&&typeof v==="object"&&!Array.isArray(v)?v as Obj:undefined;
const text=(o:Obj,...keys:string[])=>{for(const key of keys){const v=o[key];if(v!==undefined&&v!==null&&String(v).trim())return String(v).trim();}return null;};
const amount=(o:Obj,...keys:string[])=>{const v=text(o,...keys);if(v===null)return null;const n=Number(v.replace(/,/gu,""));return Number.isSafeInteger(n)?n:null;};
const list=(v:unknown):Obj[]=>Array.isArray(v)?v.map(obj).filter((x):x is Obj=>!!x):obj(v)?[obj(v)!]:[];
const delimited=(value:unknown,fields:string[]):Obj[]=>typeof value!=="string"||!value.trim()?[]:value.trim().replace(/^\[/u,"").replace(/\]$/u,"").split(/\]\s*,?\s*\[/u).map(row=>Object.fromEntries(row.split("^").map((cell,index)=>[fields[index]!,cell])));
function nestedList(root:Obj,names:string[],fields:string[]):Obj[]{for(const name of names){const value=root[name],direct=list(value);if(direct.length)return direct;const encoded=delimited(value,fields);if(encoded.length)return encoded;const record=obj(value);if(record){for(const key of ["item","items"]){const nested=list(record[key]);if(nested.length)return nested;}}}return[];}
export function lifecyclePayload(parsed:unknown):Obj|undefined{const r=obj(parsed),response=obj(r?.response),body=obj(response?.body);if(!body)return undefined;const items=body.items,itemsObj=obj(items);return list(items)[0]??list(itemsObj?.item)[0];}
export function saveLifecycle(db:DatabaseSync,args:{bidNoticeId:number;rawItemId:number;payload:Obj;collectedAt:string}){
 const p=args.payload,bidNo=text(p,"bidNtceNo","bidPblancNo")!,bidOrd=text(p,"bidNtceOrd","bidPblancOrd");
 const awards=nestedList(p,["bidwinrInfoList","bidwinrInfos","scsbidInfoList"],["ordinal","bidwinrNm","bidwinrBizno","bidwinrCeoNm","sucsfbidAmt","sucsfbidRate","prtcptCnum","opengDt"]),contracts=nestedList(p,["cntrctInfoList","cntrctInfos"],["ordinal","cntrctNo","cntrctNm","cntrctInsttNm","dminsttNm","cntrctMthdNm","cntrctAmt","cntrctDt"]);
 db.exec("BEGIN IMMEDIATE");try{
  const old=db.prepare("SELECT lifecycle_record_id id FROM lifecycle_record WHERE bid_notice_id=?").get(args.bidNoticeId)as{id:number}|undefined;
  let id=old?.id;if(old){db.prepare("DELETE FROM lifecycle_award WHERE lifecycle_record_id=?").run(old.id);db.prepare("DELETE FROM lifecycle_contract WHERE lifecycle_record_id=?").run(old.id);db.prepare(`UPDATE lifecycle_record SET order_plan_no=?,order_plan_unified_no=?,prior_specification_registration_no=?,bid_ntce_no=?,bid_ntce_ord=?,procurement_request_no=?,bid_ntce_name=?,source_raw_item_id=?,collected_at=? WHERE lifecycle_record_id=?`).run(text(p,"orderPlanNo","bsnsPlanNo"),text(p,"orderPlanUntyNo","orderPlanUnifiedNo","bsnsPlanUntyNo"),text(p,"bfSpecRgstNo","priorSpecRgstNo"),bidNo,bidOrd,text(p,"prcrmntReqNo","prcmntReqNo"),text(p,"bidNtceNm","bidNtceName"),args.rawItemId,args.collectedAt,old.id);}else{id=Number(db.prepare(`INSERT INTO lifecycle_record(bid_notice_id,order_plan_no,order_plan_unified_no,prior_specification_registration_no,bid_ntce_no,bid_ntce_ord,procurement_request_no,bid_ntce_name,source_raw_item_id,source_operation,collected_at)VALUES(?,?,?,?,?,?,?,?,?,'getCntrctProcssIntgOpenThng',?)`).run(args.bidNoticeId,text(p,"orderPlanNo","bsnsPlanNo"),text(p,"orderPlanUntyNo","orderPlanUnifiedNo","bsnsPlanUntyNo"),text(p,"bfSpecRgstNo","priorSpecRgstNo"),bidNo,bidOrd,text(p,"prcrmntReqNo","prcmntReqNo"),text(p,"bidNtceNm","bidNtceName"),args.rawItemId,args.collectedAt).lastInsertRowid);}
  if(id===undefined)throw new Error("LIFECYCLE_ID_MISSING");const lifecycleId=id;let matchedAwards=0,matchedContracts=0,unmatched=0,ambiguous=0;
  awards.forEach((a,i)=>{const winner=text(a,"bidwinrNm","winnerName","opengCorpNm"),business=text(a,"bidwinrBizno","bizno","winnerBusinessNo"),bidAmount=amount(a,"sucsfbidAmt","bidwinrAmt","successfulBidAmount"),opening=text(a,"opengDt","rlOpengDt"),r=db.prepare(`INSERT INTO lifecycle_award(lifecycle_record_id,ordinal,winner_name,winner_business_no,winner_ceo_name,successful_bid_amount,successful_bid_rate,participant_count,opening_datetime,raw_json)VALUES(?,?,?,?,?,?,?,?,?,?)`).run(lifecycleId,i,winner,business,text(a,"bidwinrCeoNm","rprsntvNm"),bidAmount,text(a,"sucsfbidRate","bidwinrRate"),amount(a,"prtcptCnum","participantCount"),opening,JSON.stringify(a)),aid=Number(r.lastInsertRowid);let matches:{id:number}[]=[];if(bidNo&&bidOrd&&business&&bidAmount!==null)matches=db.prepare(`SELECT award_result_id id FROM award_result WHERE bid_notice_id=? AND bid_ntce_no=? AND bid_ntce_ord=? AND replace(winner_business_no,'-','')=replace(?,'-','') AND successful_bid_amount=? ORDER BY award_result_id`).all(args.bidNoticeId,bidNo,bidOrd,business,bidAmount)as{id:number}[];const match=matches.length===1?matches[0]:undefined,reason=matches.length>1?"multiple_exact_candidates":!bidNo||!bidOrd||!business||bidAmount===null?"incomplete_match_keys":"no_exact_candidate";if(match)matchedAwards++;else if(matches.length>1)ambiguous++;else unmatched++;db.prepare(`INSERT INTO bid_award_link VALUES(?,?,?,'official_integrated_api',?,?,?,?)`).run(args.bidNoticeId,aid,match?.id??null,match?"official_matched":"official_unmatched",JSON.stringify({operation:LIFECYCLE_OPERATION,matchKeys:["bidNtceNo","bidNtceOrd","winnerBusinessNo","successfulBidAmount"],...(!match&&{unmatchedReason:reason,candidateCount:matches.length})}),args.collectedAt,args.collectedAt);db.prepare("INSERT INTO lifecycle_group_member VALUES(?,'award',?,'official_integrated_api')").run(lifecycleId,aid);});
  contracts.forEach((c,i)=>{const contractNo=text(c,"cntrctNo","contractNo"),contractAmount=amount(c,"cntrctAmt","contractAmount"),contractDate=text(c,"cntrctDt","contractDate"),r=db.prepare(`INSERT INTO lifecycle_contract(lifecycle_record_id,ordinal,contract_no,contract_name,contract_institution_name,contract_method_name,contract_amount,contract_date,raw_json)VALUES(?,?,?,?,?,?,?,?,?)`).run(lifecycleId,i,contractNo,text(c,"cntrctNm","contractName"),text(c,"cntrctInsttNm","contractInstitutionName"),text(c,"cntrctMthdNm","contractMethodName"),contractAmount,contractDate,JSON.stringify(c)),cid=Number(r.lastInsertRowid),matches=contractNo?db.prepare("SELECT contract_result_id id FROM contract_result WHERE decision_contract_no=? ORDER BY contract_result_id").all(contractNo)as{id:number}[]:[],match=matches.length===1?matches[0]:undefined,reason=matches.length>1?"multiple_decision_contract_candidates":contractNo?"no_decision_contract_candidate":"missing_contract_number";if(match)matchedContracts++;else if(matches.length>1)ambiguous++;else unmatched++;db.prepare(`INSERT INTO bid_contract_link VALUES(?,?,?,'official_integrated_api',?,?,?,?)`).run(args.bidNoticeId,cid,match?.id??null,match?"official_matched":"official_unmatched",JSON.stringify({operation:LIFECYCLE_OPERATION,matchKeys:["cntrctNo=decision_contract_no"],...(!match&&{unmatchedReason:reason,candidateCount:matches.length})}),args.collectedAt,args.collectedAt);db.prepare("INSERT INTO lifecycle_group_member VALUES(?,'contract',?,'official_integrated_api')").run(lifecycleId,cid);});
  db.exec("COMMIT");return{awards:awards.length,contracts:contracts.length,matchedAwards,matchedContracts,unmatched,ambiguous};
 }catch(e){db.exec("ROLLBACK");throw e;}
}
