import type {DatabaseSync} from "node:sqlite";
import {createHash} from "node:crypto";

export const OPENING_SERVICE="ScsbidInfoService";
export type OpeningIdentity={bidNtceNo:string;bidNtceOrd:string;bidClsfcNo:string;rbidNo:string};

function text(raw:Record<string,unknown>,...keys:string[]):string|null{for(const key of keys){const v=raw[key];if(typeof v==="string"&&v.trim()!=="")return v.trim();if(typeof v==="number"&&Number.isFinite(v))return String(v);}return null;}
function required(raw:Record<string,unknown>,key:string):string{const value=text(raw,key);if(value===null)throw new Error(`OPENING_NORMALIZATION_ERROR: missing ${key}`);return value;}
function integer(raw:Record<string,unknown>,...keys:string[]):number|null{const value=text(raw,...keys);if(value===null)return null;if(!/^-?\d+$/u.test(value))throw new Error(`OPENING_NORMALIZATION_ERROR: invalid integer ${keys[0]}`);const n=Number(value);if(!Number.isSafeInteger(n))throw new Error(`OPENING_NORMALIZATION_ERROR: unsafe integer ${keys[0]}`);return n;}
export function openingIdentity(raw:Record<string,unknown>):OpeningIdentity{return{bidNtceNo:required(raw,"bidNtceNo"),bidNtceOrd:required(raw,"bidNtceOrd"),bidClsfcNo:required(raw,"bidClsfcNo"),rbidNo:required(raw,"rbidNo")};}

export function normalizeOpeningRawItem(db:DatabaseSync,rawItemId:number,operation:string,observedAt:string):void{
 const row=db.prepare("SELECT service,operation,canonical_json FROM api_raw_item WHERE raw_item_id=?").get(rawItemId) as {service:string;operation:string;canonical_json:string}|undefined;
 if(!row||row.service!==OPENING_SERVICE||row.operation!==operation)throw new Error("RAW item is not from the requested opening endpoint");
 const raw=JSON.parse(row.canonical_json) as Record<string,unknown>,i=openingIdentity(raw),key=[i.bidNtceNo,i.bidNtceOrd,i.bidClsfcNo,i.rbidNo],fingerprint=createHash("sha256").update(row.canonical_json).digest("hex");
 if(operation==="getOpengResultListInfoOpengCompt")db.prepare(`INSERT INTO opening_participant(bid_ntce_no,bid_ntce_ord,bid_clsfc_no,rbid_no,opening_result_type_name,opening_rank,bidder_business_no,bidder_name,bidder_ceo_name,bid_amount,bid_rate,remark,draw_no_1,draw_no_2,bid_datetime,item_fingerprint,source_raw_item_id,observed_at)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT DO UPDATE SET source_raw_item_id=excluded.source_raw_item_id,observed_at=excluded.observed_at`).run(...key,text(raw,"opengRsltDivNm"),text(raw,"opengRank"),text(raw,"prcbdrBizno"),text(raw,"prcbdrNm"),text(raw,"prcbdrCeoNm"),integer(raw,"bidprcAmt"),text(raw,"bidprcrt"),text(raw,"rmrk"),text(raw,"drwtNo1"),text(raw,"drwtNo2"),text(raw,"bidprcDt"),fingerprint,rawItemId,observedAt);
 else if(operation==="getOpengResultListInfoThngPreparPcDetail")db.prepare(`INSERT INTO opening_preliminary_price(bid_ntce_no,bid_ntce_ord,bid_clsfc_no,rbid_no,planned_price,basis_amount,total_preliminary_price_count,preliminary_price_sequence,preliminary_price,selected_yn,selected_count,actual_opening_datetime,upper_count_from_basis_amount,preliminary_price_created_datetime,item_fingerprint,source_raw_item_id,observed_at)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT DO UPDATE SET source_raw_item_id=excluded.source_raw_item_id,observed_at=excluded.observed_at`).run(...key,integer(raw,"plnprc","plnprcAmt"),integer(raw,"bssamt"),integer(raw,"totRsrvtnPrceNum"),text(raw,"compnoRsrvtnPrceSno","rsrvtnPrceSno"),integer(raw,"bsisPlnprc","rsrvtnPrce"),text(raw,"drwtYn"),integer(raw,"drwtCnt"),text(raw,"rlOpengDt"),integer(raw,"bssamtBssUpNum"),text(raw,"rsrvtnPrceMkngDt"),fingerprint,rawItemId,observedAt);
 else if(operation==="getOpengResultListInfoFailing")db.prepare(`INSERT INTO opening_failure_event(bid_ntce_no,bid_ntce_ord,bid_clsfc_no,rbid_no,opening_result_type_name,failure_reason,item_fingerprint,source_raw_item_id,observed_at)VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT DO UPDATE SET source_raw_item_id=excluded.source_raw_item_id,observed_at=excluded.observed_at`).run(...key,text(raw,"opengRsltDivNm"),text(raw,"flrRsn","failingRsn","rmrk"),fingerprint,rawItemId,observedAt);
 else if(operation==="getOpengResultListInfoRebid")db.prepare(`INSERT INTO opening_rebid_event(bid_ntce_no,bid_ntce_ord,bid_clsfc_no,rbid_no,opening_result_type_name,bid_deadline_datetime,opening_datetime,rebid_reason,consortium_agreement_deadline_datetime,item_fingerprint,source_raw_item_id,observed_at)VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT DO UPDATE SET source_raw_item_id=excluded.source_raw_item_id,observed_at=excluded.observed_at`).run(...key,text(raw,"opengRsltDivNm"),text(raw,"bidClseDt"),text(raw,"opengDt","rlOpengDt"),text(raw,"rbidRsn","rebidRsn","rmrk"),text(raw,"cmmnSpldmdAgrmntClseDt"),fingerprint,rawItemId,observedAt);
 else throw new Error(`Unsupported opening operation: ${operation}`);
}
