import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { DatabaseSync } from "node:sqlite";
import type { KonepsResponse } from "../koneps/types.js";
import { KonepsError } from "../koneps/errors.js";
import { openMarketDatabase, migrateMarketDatabase, CURRENT_SCHEMA_VERSION } from "../storage/database.js";
import { MIGRATIONS } from "../storage/migrations.js";
import { runManualCollection,type CollectorClient } from "./collector.js";
import { assertLongRangeAllowed, chunkCount, chunks, incrementalRange, incrementalSmokeRange, initialDateTimeRange, initialRange, PRACTICAL_LOWER_BOUND,type CollectionPlan } from "./planner.js";
import { parseManualCliArgs } from "./cli.js";
import { checkpoint,enqueueWork } from "./state.js";

async function live(name:string):Promise<Record<string,unknown>>{const f=JSON.parse(await readFile(new URL(`../../collector/koneps/fixtures/live-sanitized/${name}`,import.meta.url),"utf8")) as {response:{body:{items:Array<Record<string,unknown>>}}};return f.response.body.items[0]!;}
function response(operation:string,page:number,items:Array<Record<string,unknown>>,total=items.length):KonepsResponse{
  const parsedJson={response:{header:{resultCode:"00",resultMsg:"OK"},body:{items,pageNo:page,numOfRows:5,totalCount:total}}}; const body=JSON.stringify(parsedJson); const at=`2026-08-14T00:00:0${Math.min(page,9)}.000Z`;
  return {status:200,headers:{"content-type":"application/json"},bodyBytes:new TextEncoder().encode(body),bodyText:body,parsedJson,envelope:{resultCode:"00",resultMsg:"OK",pageNo:page,numOfRows:5,totalCount:total},receivedAt:at,durationMs:1,metadata:{service:"BidPublicInfoService",operation,redactedUrl:`https://example.test/${operation}?ServiceKey=[REDACTED]&pageNo=${page}`,pageNo:page,numOfRows:5,startedAt:at,finishedAt:at,durationMs:1,attemptCount:1,retryCount:0,httpStatus:200,resultCode:"00",resultMsg:"OK"}};
}
class MockClient implements CollectorClient{
  calls:Array<{operation:string;params:any}>=[]; constructor(readonly handler:(operation:string,params:any,calls:number)=>KonepsResponse|Promise<KonepsResponse>){}
  async request(operation:any,params:any):Promise<KonepsResponse>{this.calls.push({operation:operation.path,params});return this.handler(operation.path,params,this.calls.length);}
}
function plan(start="2026-08-13T00:00:00",end="2026-08-13T23:59:00",mode:"initial"|"incremental"="initial"):CollectionPlan{return {mode,requestedRange:mode==="initial"?{start,end}:null,effectiveRange:{start,end},checkpoint:null,overlapMinutes:mode==="incremental"?1440:0,chunkMinutes:1440,chunkCount:chunkCount({start,end}),operations:["getBidPblancListInfoThngPPSSrch","getBidPblancListInfoThngPurchsObjPrdct","getBidPblancListInfoThngBsisAmount"]};}
async function standardClient(notices:Array<Record<string,unknown>>,options:{failItemOnce?:boolean;changedNotice?:boolean}={}):Promise<MockClient>{const item=await live("bid-item.json"),basis=await live("bid-basis-amount.json");let failed=false;return new MockClient((op,p)=>{if(op==="getBidPblancListInfoThngPPSSrch"){const page=Number(p.pageNo),slice=notices.slice((page-1)*5,page*5).map(n=>options.changedNotice?{...n,bidNtceNm:"changed"}:n);return response(op,page,slice,notices.length);}if(op==="getBidPblancListInfoThngPurchsObjPrdct"){if(options.failItemOnce&&!failed){failed=true;throw new KonepsError("network","KONEPS network request failed");}return response(op,1,[{...item,bidNtceNo:p.bidNtceNo,bidNtceOrd:p.bidNtceOrd}],1);}return response(op,1,[{...basis,bidNtceNo:p.bidNtceNo,bidNtceOrd:"000"}],1);});}

test("migration v4 upgrades v3 and fresh/repeated opens remain valid",()=>{const db=new DatabaseSync(":memory:");db.exec("PRAGMA foreign_keys=ON;BEGIN");for(const m of MIGRATIONS.slice(0,3))db.exec(m.sql);db.exec("PRAGMA user_version=3;COMMIT");migrateMarketDatabase(db);migrateMarketDatabase(db);assert.equal(CURRENT_SCHEMA_VERSION,4);assert.ok(db.prepare("SELECT name FROM sqlite_master WHERE name='collector_checkpoint'").get());assert.ok(db.prepare("SELECT name FROM sqlite_master WHERE name='collector_work_item'").get());db.close();});
test("initial validation uses KST, lower bound, ordering, future protection, and long-range confirmation",()=>{const now=new Date("2026-08-14T03:00:00Z");assert.equal(initialRange("2001-01-01","2001-01-01",now).start,PRACTICAL_LOWER_BOUND);assert.throws(()=>initialRange("2000-12-31","2001-01-01",now),/BEFORE_2001/u);assert.throws(()=>initialRange("2026-08-13","2026-08-12",now),/START_AFTER/u);assert.throws(()=>initialRange("2026-08-15","2026-08-15",now),/FUTURE_KST/u);assert.throws(()=>assertLongRangeAllowed(initialRange("2001-01-01","2026-08-13",now),false),/LONG_RANGE/u);});
test("long-range planner is lazy and chunks one KST day without allocating all work",()=>{const range={start:"2001-01-01T00:00:00",end:"2026-08-14T23:59:00"};assert.ok(chunkCount(range)>9000);const iterator=chunks(range);assert.deepEqual(iterator.next().value,{start:"2001-01-01T00:00:00",end:"2001-01-01T23:59:00"});});
test("incremental without checkpoint fails before any client exists and overlap clamps to lower bound",()=>{assert.throws(()=>incrementalRange(undefined,new Date()),/INITIAL_RANGE_REQUIRED/u);assert.equal(incrementalRange(PRACTICAL_LOWER_BOUND,new Date("2001-01-01T00:30:00Z")).start,PRACTICAL_LOWER_BOUND);});
test("empty initial chunk succeeds and advances checkpoint with zero enrichment",async()=>{const db=openMarketDatabase(":memory:");const client=new MockClient((op,p)=>response(op,p.pageNo,[],0));const result=await runManualCollection({database:db,client,plan:plan(),now:()=>new Date("2026-08-14T00:00:00Z")});assert.equal(result.status,"succeeded");assert.equal(result.checkpoint,"2026-08-13T23:59:00");assert.equal(client.calls.length,1);assert.equal(checkpoint(db),result.checkpoint!);db.close();});
test("multi-page discovery processes 5 plus short final page and deduplicates work identities",async()=>{const base=await live("bid-notice.json");const notices=Array.from({length:6},(_,i)=>({...base,bidNtceNo:`N${i}`,bidNtceOrd:"000"}));const db=openMarketDatabase(":memory:"),client=await standardClient(notices);const result=await runManualCollection({database:db,client,plan:plan(),now:()=>new Date("2026-08-14T00:00:00Z")});assert.equal(result.status,"succeeded");assert.equal(result.noticesDiscovered,6);assert.equal((db.prepare("SELECT count(*) n FROM bid_notice").get() as {n:number}).n,6);assert.equal((db.prepare("SELECT count(*) n FROM collector_work_item").get() as {n:number}).n,12);assert.equal(client.calls.filter(c=>c.operation==="getBidPblancListInfoThngPPSSrch").length,2);db.close();});
test("failed first chunk creates no checkpoint while middle failure retains prior checkpoint",async()=>{for(const failCall of [1,2]){const db=openMarketDatabase(":memory:");let discovery=0;const client=new MockClient((op,p)=>{if(op.includes("PPSSrch")&&++discovery===failCall)throw new KonepsError("network","safe failure");return response(op,p.pageNo,[],0);});const result=await runManualCollection({database:db,client,plan:plan("2026-08-12T00:00:00","2026-08-13T23:59:00"),now:()=>new Date("2026-08-14T00:00:00Z")});assert.equal(checkpoint(db),failCall===1?undefined:"2026-08-12T23:59:00");assert.equal(result.status,failCall===1?"failed":"partial");db.close();}});
test("enrichment failure is retained, discovery checkpoint advances, and next manual run retries it",async()=>{const notice=await live("bid-notice.json");const db=openMarketDatabase(":memory:");const first=await standardClient([notice],{failItemOnce:true});const a=await runManualCollection({database:db,client:first,plan:plan(),now:()=>new Date("2026-08-14T00:00:00Z")});assert.equal(a.status,"partial");assert.equal(checkpoint(db),"2026-08-13T23:59:00");assert.equal((db.prepare("SELECT count(*) n FROM collector_work_item WHERE status='failed'").get() as {n:number}).n,1);const second=await standardClient([]);const b=await runManualCollection({database:db,client:second,plan:plan("2026-08-13T00:00:00","2026-08-13T23:59:00","incremental"),now:()=>new Date("2026-08-14T00:00:00Z")});assert.equal(b.status,"succeeded");assert.equal((db.prepare("SELECT count(*) n FROM collector_work_item WHERE status='failed'").get() as {n:number}).n,0);db.close();});
test("overlap replay is unchanged, changed notice creates revision, and offline DB remains queryable",async()=>{const notice=await live("bid-notice.json");const db=openMarketDatabase(":memory:");await runManualCollection({database:db,client:await standardClient([notice]),plan:plan(),now:()=>new Date("2026-08-14T00:00:00Z")});await runManualCollection({database:db,client:await standardClient([notice],{changedNotice:true}),plan:plan("2026-08-13T00:00:00","2026-08-13T23:59:00","incremental"),now:()=>new Date("2026-08-14T01:00:00Z")});assert.equal((db.prepare("SELECT count(*) n FROM bid_notice_revision").get() as {n:number}).n,1);assert.ok(db.prepare("SELECT bid_ntce_no FROM bid_notice").get());assert.ok(db.prepare("SELECT * FROM bid_item").get());assert.ok(db.prepare("SELECT * FROM bid_basis_amount").get());db.close();});
test("work idempotency is scoped to run and cancellation stops at a safe boundary",async()=>{const db=openMarketDatabase(":memory:");db.prepare("INSERT INTO collector_run(run_id,mode,status,started_at,app_version,parser_version,schema_version) VALUES('r','period','running','t','v','v',4)").run();assert.equal(enqueueWork(db,"r","N","000","t"),2);assert.equal(enqueueWork(db,"r","N","000","t"),0);const result=await runManualCollection({database:db,client:new MockClient(()=>{throw new Error("must not call");}),plan:plan(),isCancelled:()=>true,now:()=>new Date("2026-08-14T00:00:00Z")});assert.equal(result.status,"cancelled");db.close();});
test("smoke CLI accepts a minute range only with paired positive safety limits",()=>{const args=parseManualCliArgs(["initial","--start-datetime","2026-08-13T16:38","--end-datetime","2026-08-13T16:38","--smoke-max-notices","2","--smoke-max-api-calls","10"]);assert.equal(args.smokeMaxNotices,2);assert.deepEqual(initialDateTimeRange(args.startDatetime!,args.endDatetime!,new Date("2026-08-14T00:00:00Z")),{start:"2026-08-13T16:38:00",end:"2026-08-13T16:38:00"});assert.throws(()=>parseManualCliArgs(["initial","--start-datetime","2026-08-13T16:38","--end-datetime","2026-08-13T16:38","--smoke-max-notices","2"]),/supplied together/u);});
test("smoke notice limit stops after page one and never advances checkpoint",async()=>{const base=await live("bid-notice.json");const notices=[0,1,2].map(i=>({...base,bidNtceNo:`S${i}`}));const db=openMarketDatabase(":memory:"),client=await standardClient(notices);const result=await runManualCollection({database:db,client,plan:plan("2026-08-13T16:38:00","2026-08-13T16:38:00"),maxDiscoveredNotices:2,maxApiCalls:10,now:()=>new Date("2026-08-14T00:00:00Z")});assert.equal(result.status,"failed");assert.equal(client.calls.length,1);assert.equal(checkpoint(db),undefined);assert.equal((db.prepare("SELECT count(*) n FROM bid_notice").get() as {n:number}).n,0);db.close();});
test("smoke API call limit is a hard logical-request boundary",async()=>{const notice=await live("bid-notice.json");const db=openMarketDatabase(":memory:"),client=await standardClient([notice]);const result=await runManualCollection({database:db,client,plan:plan("2026-08-13T16:38:00","2026-08-13T16:38:00"),maxDiscoveredNotices:2,maxApiCalls:2,now:()=>new Date("2026-08-14T00:00:00Z")});assert.equal(result.status,"partial");assert.equal(client.calls.length,2);assert.equal(checkpoint(db),"2026-08-13T16:38:00");db.close();});
test("incremental smoke range limits execution without changing the 24-hour production calculation",()=>{const now=new Date("2026-08-14T00:00:00Z"),cp="2026-08-13T16:38:00";const production=incrementalRange(cp,now);assert.equal(production.start,"2026-08-12T16:38:00");assert.deepEqual(incrementalSmokeRange(production,cp,"2026-08-13T16:38","2026-08-13T16:39",now),{start:"2026-08-13T16:38:00",end:"2026-08-13T16:39:00"});assert.throws(()=>incrementalSmokeRange(production,cp,"2026-08-13T16:39","2026-08-13T16:40",now),/MUST_INCLUDE_CHECKPOINT/u);});
