import type { DatabaseSync } from "node:sqlite";
import type { KonepsOperation, KonepsRequestParams, KonepsResponse } from "../koneps/types.js";
import { CONTRACT_DETAIL_OPERATION, CONTRACT_SEARCH_OPERATION } from "../koneps/endpoints.js";
import { normalizeEvidenceBackedContractResults } from "../normalization/contract-repository.js";
import { upsertContractHeader, upsertContractItem } from "../normalization/contract-source-derived.js";
import { persistRawPage, startCollectorRun, startOperationRun } from "../storage/raw-persistence.js";

export interface ContractClient { request<T extends KonepsRequestParams>(operation: KonepsOperation<T>, params: T): Promise<KonepsResponse> }
function save(db:DatabaseSync,operationRunId:string,response:KonepsResponse,operation:KonepsOperation<any>,params:Record<string,unknown>,parserVersion:string){return persistRawPage(db,{operationRunId,service:operation.service,operation:operation.path,requestedAt:response.metadata.startedAt,completedAt:response.receivedAt,durationMs:response.durationMs,httpStatus:response.status,resultCode:response.envelope.resultCode,resultMsg:response.envelope.resultMsg,pageNo:Number(params.pageNo),numOfRows:Number(params.numOfRows),totalCount:response.envelope.totalCount??0,requestMetadata:params,requestUrl:response.metadata.redactedUrl,responseBytes:response.bodyBytes,contentType:response.headers["content-type"],encoding:"utf-8",parsedJson:response.parsedJson,parserVersion});}

export async function collectContractRange(o:{database:DatabaseSync;client:ContractClient;discoveryName:string;targetCodes:readonly string[];range:{start:string;end:string};isCancelled?:()=>boolean;onProgress?:(p:{page:number;totalCount:number;processed:number})=>void}){
 if(o.targetCodes.some(code=>!/^\d{8}$/.test(code)))throw new Error("INVALID_CONTRACT_TARGET");
 const now=()=>new Date().toISOString(),parserVersion="contract-source-v3",runId=startCollectorRun(o.database,{mode:"period",requestedRangeStart:o.range.start,requestedRangeEnd:o.range.end,startedAt:now(),appVersion:"0.1.0",parserVersion});
 const discoveryRun=startOperationRun(o.database,{runId,service:CONTRACT_SEARCH_OPERATION.service,operation:CONTRACT_SEARCH_OPERATION.path,queryBasis:"contract_date+name:discovery-only",effectiveRangeStart:o.range.start,effectiveRangeEnd:o.range.end,startedAt:now()}),detailRun=startOperationRun(o.database,{runId,service:CONTRACT_DETAIL_OPERATION.service,operation:CONTRACT_DETAIL_OPERATION.path,queryBasis:"untyCntrctNo+prdctClsfcNo:8-digit-target",startedAt:now()});
 let page=1,total=0,processed=0;
 try{do{if(o.isCancelled?.())break;const date=(v:string)=>v.slice(0,10).replace(/-/gu,""),params={pageNo:page,numOfRows:100,type:"json"as const,inqryDiv:"1"as const,inqryBgnDate:date(o.range.start),inqryEndDate:date(o.range.end),prdctClsfcNoNm:o.discoveryName},response=await o.client.request(CONTRACT_SEARCH_OPERATION,params),saved=save(o.database,discoveryRun,response,CONTRACT_SEARCH_OPERATION,params,parserVersion);total=response.envelope.totalCount??saved.actualItemCount;for(const rawId of saved.rawItemIds){const at=now(),headerId=upsertContractHeader(o.database,rawId,at),state=o.database.prepare("SELECT status FROM contract_detail_state WHERE contract_header_id=?").get(headerId)as{status:string};if(state.status!=="SUCCESS")await enrich(o.database,o.client,detailRun,headerId,o.targetCodes,parserVersion,now);normalizeEvidenceBackedContractResults(o.database,rawId,headerId,o.targetCodes,now());processed++;}o.onProgress?.({page,totalCount:total,processed});page++;}while(processed<total);const status=o.isCancelled?.()?"cancelled":"succeeded",at=now();for(const id of[discoveryRun,detailRun])o.database.prepare("UPDATE collector_operation_run SET status=?,completed_at=? WHERE operation_run_id=?").run(status,at,id);o.database.prepare("UPDATE collector_run SET status=?,completed_at=? WHERE run_id=?").run(status,at,runId);return{runId,status,total,processed};}catch(error){const at=now();for(const id of[discoveryRun,detailRun])o.database.prepare("UPDATE collector_operation_run SET status='failed',completed_at=?,error_summary='redacted contract collection error' WHERE operation_run_id=? AND status='running'").run(at,id);o.database.prepare("UPDATE collector_run SET status='failed',completed_at=?,error_summary='redacted contract collection error' WHERE run_id=?").run(at,runId);throw error;}}

async function enrich(db:DatabaseSync,client:ContractClient,detailRun:string,headerId:number,targetCodes:readonly string[],parserVersion:string,now:()=>string){const header=db.prepare("SELECT unty_cntrct_no unty FROM contract_header WHERE contract_header_id=?").get(headerId)as{unty:string};db.prepare("UPDATE contract_detail_state SET status='RUNNING',attempts=attempts+1,last_attempt_at=?,last_error_summary=NULL,updated_at=? WHERE contract_header_id=?").run(now(),now(),headerId);try{let page=1,seen=0,total=0;do{const params={pageNo:page,numOfRows:100,type:"json"as const,inqryDiv:"2"as const,untyCntrctNo:header.unty},response=await client.request(CONTRACT_DETAIL_OPERATION,params),saved=save(db,detailRun,response,CONTRACT_DETAIL_OPERATION,params,parserVersion);total=response.envelope.totalCount??saved.actualItemCount;for(const rawId of saved.rawItemIds){upsertContractItem(db,headerId,rawId,targetCodes,now());seen++;}page++;}while(seen<total);db.prepare("UPDATE contract_detail_state SET status='SUCCESS',completed_at=?,updated_at=? WHERE contract_header_id=?").run(now(),now(),headerId);}catch(error){db.prepare("UPDATE contract_detail_state SET status='FAILED',last_error_summary='contract detail lookup failed',updated_at=? WHERE contract_header_id=?").run(now(),headerId);throw error;}}
