import assert from "node:assert/strict";
import test from "node:test";
import { openMarketDatabase } from "../storage/database.js";
import { applyContractReset, planContractReset } from "./contract-reset.js";

test("contract reset deletes only contract normalized/checkpoint state and preserves bid award raw",()=>{const db=openMarketDatabase(":memory:");db.exec("PRAGMA foreign_keys=OFF");db.exec(`
 INSERT INTO api_raw_item(raw_item_id,service,operation,item_sha256,canonical_json,parser_version,first_seen_at)VALUES(1,'CntrctInfoService','getCntrctInfoListThngPPSSrch','aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa','{}','t','t');
 INSERT INTO contract_result(contract_result_id,target_detailed_product_class_no,decision_contract_no,source_raw_item_id,source_operation,semantic_row_hash,semantic_state_json,parse_warnings_json,first_normalized_at,last_normalized_at)VALUES(1,'4015155301','D',1,'getCntrctInfoListThngPPSSrch','bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb','{}','[]','t','t');
 INSERT INTO contract_header(contract_header_id,unty_cntrct_no,source_raw_item_id,source_operation,raw_json,first_seen_at,updated_at)VALUES(1,'U',1,'getCntrctInfoListThngPPSSrch','{}','t','t');
 INSERT INTO contract_detail_state(contract_header_id,status,updated_at)VALUES(1,'SUCCESS','t');
 INSERT INTO contract_collection_job(job_id,status,cutoff_at,created_at,updated_at)VALUES('j','paused','t','t','t');
 INSERT INTO contract_collection_target(job_id,dtil_prdct_clsfc_no,target_name,status,updated_at)VALUES('j','4015155301','n','paused','t');
 INSERT INTO contract_month_probe(job_id,dtil_prdct_clsfc_no,month,range_start,range_end,total_count,status,probed_at)VALUES('j','4015155301','2026-01','a','b',1,'collected','t');
 INSERT INTO bid_notice(bid_notice_id,bid_ntce_no,bid_ntce_ord,detailed_product_class_no,source_raw_item_id,source_operation,semantic_row_hash,semantic_state_json,parse_warnings_json,first_normalized_at,last_normalized_at)VALUES(1,'B','000','4015155301',1,'getBidPblancListInfoThngPPSSrch','cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc','{}','[]','t','t');
 `);const before=planContractReset(db);assert.equal(before.deleteRows.contract_result,1);assert.equal(before.deleteRows.contract_header,1);const result=applyContractReset(db,before.planToken);assert.equal(result.deletedRows.contract_result,1);assert.equal((db.prepare("SELECT count(*) n FROM api_raw_item").get()as{n:number}).n,1);assert.equal((db.prepare("SELECT count(*) n FROM bid_notice").get()as{n:number}).n,1);assert.equal((db.prepare("SELECT count(*) n FROM contract_result").get()as{n:number}).n,0);assert.equal((db.prepare("SELECT count(*) n FROM contract_header").get()as{n:number}).n,0);db.close();});

test("contract reset rolls back when plan changed or procurement group references exist",()=>{const db=openMarketDatabase(":memory:"),plan=planContractReset(db);db.prepare("INSERT INTO procurement_group(representative_title,item_category,has_bid,has_award,has_contract,bid_count,award_count,contract_count,match_status,rebuilt_at)VALUES('x','unknown',0,0,1,0,0,1,'UNLINKED','t')").run();db.prepare("INSERT INTO procurement_group_member(procurement_group_id,source_type,source_id,member_role,match_method)VALUES(1,'CONTRACT',1,'RESULT','UNLINKED')").run();assert.throws(()=>applyContractReset(db,plan.planToken),/PLAN_CHANGED/u);const blocked=planContractReset(db);assert.throws(()=>applyContractReset(db,blocked.planToken),/BLOCKED_BY_PROCUREMENT_GROUP/u);assert.equal((db.prepare("SELECT count(*) n FROM procurement_group_member").get()as{n:number}).n,1);db.close();});

test("completed contract collection jobs are history while resumable jobs are reset",()=>{const db=openMarketDatabase(":memory:");for(const [id,status]of[["done","completed"],["resume","paused"]]as const)db.prepare("INSERT INTO contract_collection_job(job_id,status,cutoff_at,created_at,updated_at,completed_at)VALUES(?,?,?,?,?,?)").run(id,status,"t","t","t",status==="completed"?"t":null);const plan=planContractReset(db);assert.equal(plan.deleteRows.contract_collection_job,1);applyContractReset(db,plan.planToken);assert.deepEqual(db.prepare("SELECT job_id,status FROM contract_collection_job").all().map(row=>({...row})),[{job_id:"done",status:"completed"}]);db.close();});
