import type { DatabaseSync } from "node:sqlite";
import { randomUUID } from "node:crypto";
import { DISCOVERY_OPERATION, COLLECTOR_SERVICE } from "./state.js";
import { DISCOVERY_CHUNK_MINUTES, PRACTICAL_LOWER_BOUND, kstNow } from "./planner.js";

export const HISTORICAL_QUERY_BASIS="notice_posted_datetime";
export const LEASE_NAME="market-collector";
export const LEASE_TTL_MS=60_000;
type JobStatus="planned"|"running"|"paused"|"completed"|"completed_with_errors"|"failed"|"cancelled";
type ChunkStatus="pending"|"running"|"succeeded"|"failed";
export interface HistoricalJob { jobId:string; service:string; queryBasis:string; startBoundary:string; cutoffBoundary:string; direction:"forward"; chunkMinutes:number; status:JobStatus; successfulThrough:string|null; stopRequested:boolean; createdAt:string; startedAt:string|null; updatedAt:string; completedAt:string|null; lastRunId:string|null; errorSummary:string|null; }
export interface HistoricalChunk { chunkId:number; jobId:string; rangeStart:string; rangeEnd:string; status:ChunkStatus; attempts:number; startedAt:string|null; completedAt:string|null; lastRunId:string|null; errorCategory:string|null; errorSummary:string|null; }
export interface CollectorLease { leaseName:string; holderToken:string; mode:"manual"|"historical"; jobId:string|null; acquiredAt:string; heartbeatAt:string; expiresAt:string; fresh:boolean; }
const local=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}$/u;
function millis(value:string):number { if(!local.test(value)) throw new Error("INVALID_HISTORICAL_BOUNDARY"); const n=Date.parse(`${value}Z`); if(Number.isNaN(n)||new Date(n).toISOString().slice(0,19)!==value)throw new Error("INVALID_HISTORICAL_BOUNDARY"); return n; }
function boundary(value:string,endOfDay=false):string {if(/^\d{4}-\d{2}-\d{2}$/u.test(value))return `${value}T${endOfDay?"23:59":"00:00"}:00`;if(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/u.test(value))return `${value}:00`;return value;}
function iso(now:Date):string{return now.toISOString();}
function rowJob(row:any):HistoricalJob{return {jobId:row.job_id,service:row.service,queryBasis:row.query_basis,startBoundary:row.start_boundary,cutoffBoundary:row.cutoff_boundary,direction:row.direction,chunkMinutes:row.chunk_minutes,status:row.status,successfulThrough:row.successful_through,stopRequested:row.stop_requested===1,createdAt:row.created_at,startedAt:row.started_at,updatedAt:row.updated_at,completedAt:row.completed_at,lastRunId:row.last_run_id,errorSummary:row.error_summary};}
function rowChunk(row:any):HistoricalChunk{return {chunkId:row.chunk_id,jobId:row.job_id,rangeStart:row.range_start,rangeEnd:row.range_end,status:row.status,attempts:row.attempts,startedAt:row.started_at,completedAt:row.completed_at,lastRunId:row.last_run_id,errorCategory:row.error_category,errorSummary:row.error_summary};}
export function historicalJob(db:DatabaseSync,id:string):HistoricalJob|undefined {const r=db.prepare("SELECT * FROM historical_backfill_job WHERE job_id=?").get(id);return r?rowJob(r):undefined;}
export function createHistoricalJob(db:DatabaseSync,args:{start:string;cutoff:string;now:Date;chunkMinutes?:number}):HistoricalJob {
  const start=boundary(args.start); const cutoff=boundary(args.cutoff,true);
  const nowKst=kstNow(args.now); if(millis(start)<millis(PRACTICAL_LOWER_BOUND))throw new Error("HISTORICAL_START_BEFORE_2001_LOWER_BOUND"); if(millis(start)>=millis(cutoff))throw new Error("HISTORICAL_START_MUST_BE_BEFORE_CUTOFF"); if(millis(cutoff)>millis(nowKst))throw new Error("HISTORICAL_CUTOFF_IN_FUTURE_KST");
  const active=db.prepare("SELECT job_id FROM historical_backfill_job WHERE status IN ('planned','running','paused') LIMIT 1").get(); if(active)throw new Error("ACTIVE_HISTORICAL_JOB_EXISTS");
  const id=randomUUID(),at=iso(args.now),minutes=args.chunkMinutes??DISCOVERY_CHUNK_MINUTES;
  db.prepare("INSERT INTO historical_backfill_job(job_id,service,query_basis,start_boundary,cutoff_boundary,direction,chunk_minutes,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,'planned',?,?)").run(id,COLLECTOR_SERVICE,HISTORICAL_QUERY_BASIS,start,cutoff,"forward",minutes,at,at);
  return historicalJob(db,id)!;
}
export function nextHistoricalChunk(db:DatabaseSync,jobId:string):HistoricalChunk|undefined {
  const job=historicalJob(db,jobId);if(!job)throw new Error("HISTORICAL_JOB_NOT_FOUND"); const startMs=job.successfulThrough?millis(job.successfulThrough)+60_000:millis(job.startBoundary),cutoff=millis(job.cutoffBoundary);if(startMs>cutoff)return undefined;
  const end=Math.min(cutoff,startMs+job.chunkMinutes*60_000-60_000),start=new Date(startMs).toISOString().slice(0,19),finish=new Date(end).toISOString().slice(0,19);
  db.prepare("INSERT INTO historical_backfill_chunk(job_id,range_start,range_end,status) VALUES(?,?,?,'pending') ON CONFLICT(job_id,range_start,range_end) DO NOTHING").run(jobId,start,finish);
  return rowChunk(db.prepare("SELECT * FROM historical_backfill_chunk WHERE job_id=? AND range_start=? AND range_end=?").get(jobId,start,finish));
}
export function previewHistoricalNextChunk(db:DatabaseSync,jobId:string):Pick<HistoricalChunk,"jobId"|"rangeStart"|"rangeEnd">|undefined {
  const job=historicalJob(db,jobId);if(!job)throw new Error("HISTORICAL_JOB_NOT_FOUND");const startMs=job.successfulThrough?millis(job.successfulThrough)+60_000:millis(job.startBoundary),cutoff=millis(job.cutoffBoundary);if(startMs>cutoff)return undefined;const end=Math.min(cutoff,startMs+job.chunkMinutes*60_000-60_000);return {jobId,rangeStart:new Date(startMs).toISOString().slice(0,19),rangeEnd:new Date(end).toISOString().slice(0,19)};
}
export function markHistoricalChunkRunning(db:DatabaseSync,chunkId:number,now:Date):void {db.prepare("UPDATE historical_backfill_chunk SET status='running',attempts=attempts+1,started_at=?,completed_at=NULL,error_category=NULL,error_summary=NULL WHERE chunk_id=?").run(iso(now),chunkId);}
export function completeHistoricalChunk(db:DatabaseSync,chunkId:number,now:Date,runId?:string):HistoricalJob {const chunk=rowChunk(db.prepare("SELECT * FROM historical_backfill_chunk WHERE chunk_id=?").get(chunkId));const job=historicalJob(db,chunk.jobId)!;const at=iso(now);db.exec("BEGIN IMMEDIATE");try{db.prepare("UPDATE historical_backfill_chunk SET status='succeeded',completed_at=?,last_run_id=?,error_category=NULL,error_summary=NULL WHERE chunk_id=?").run(at,runId??null,chunkId);const done=chunk.rangeEnd===job.cutoffBoundary;db.prepare("UPDATE historical_backfill_job SET successful_through=?,status=?,updated_at=?,completed_at=?,last_run_id=? WHERE job_id=?").run(chunk.rangeEnd,done?"completed":"running",at,done?at:null,runId??null,job.jobId);db.exec("COMMIT");}catch(e){db.exec("ROLLBACK");throw e;}return historicalJob(db,job.jobId)!;}
export function failHistoricalChunk(db:DatabaseSync,chunkId:number,category:string,summary:string,now:Date):void {db.prepare("UPDATE historical_backfill_chunk SET status='failed',completed_at=?,error_category=?,error_summary=? WHERE chunk_id=?").run(iso(now),category,summary,chunkId);}
function leaseRow(row:any,now:Date):CollectorLease{const expiry=Date.parse(row.expires_at);if(Number.isNaN(expiry))throw new Error("INVALID_LEASE_EXPIRY");return {leaseName:row.lease_name,holderToken:row.holder_token,mode:row.mode,jobId:row.job_id,acquiredAt:row.acquired_at,heartbeatAt:row.heartbeat_at,expiresAt:row.expires_at,fresh:expiry>now.getTime()};}
export function collectorLease(db:DatabaseSync,now:Date):CollectorLease|undefined {const r=db.prepare("SELECT * FROM collector_lease WHERE lease_name=?").get(LEASE_NAME);return r?leaseRow(r,now):undefined;}
export function acquireCollectorLease(db:DatabaseSync,args:{token:string;mode:"manual"|"historical";jobId?:string;now:Date;ttlMs?:number}):CollectorLease {const ttl=args.ttlMs??LEASE_TTL_MS,at=iso(args.now),expires=new Date(args.now.getTime()+ttl).toISOString();db.exec("BEGIN IMMEDIATE");try{const current=collectorLease(db,args.now);if(current?.fresh&&current.holderToken!==args.token)throw new Error("COLLECTOR_BUSY");db.prepare("INSERT INTO collector_lease(lease_name,holder_token,mode,job_id,acquired_at,heartbeat_at,expires_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(lease_name) DO UPDATE SET holder_token=excluded.holder_token,mode=excluded.mode,job_id=excluded.job_id,acquired_at=excluded.acquired_at,heartbeat_at=excluded.heartbeat_at,expires_at=excluded.expires_at").run(LEASE_NAME,args.token,args.mode,args.jobId??null,at,at,expires);db.exec("COMMIT");}catch(e){db.exec("ROLLBACK");throw e;}return collectorLease(db,args.now)!;}
export function heartbeatCollectorLease(db:DatabaseSync,token:string,now:Date,ttlMs=LEASE_TTL_MS):CollectorLease {const changed=db.prepare("UPDATE collector_lease SET heartbeat_at=?,expires_at=? WHERE lease_name=? AND holder_token=?").run(iso(now),new Date(now.getTime()+ttlMs).toISOString(),LEASE_NAME,token).changes;if(changed!==1)throw new Error("LEASE_NOT_HELD");return collectorLease(db,now)!;}
export function releaseCollectorLease(db:DatabaseSync,token:string):void {if(db.prepare("DELETE FROM collector_lease WHERE lease_name=? AND holder_token=?").run(LEASE_NAME,token).changes!==1)throw new Error("LEASE_NOT_HELD");}
export function requestHistoricalStop(db:DatabaseSync,id:string,now:Date):HistoricalJob {if(!historicalJob(db,id))throw new Error("HISTORICAL_JOB_NOT_FOUND");db.prepare("UPDATE historical_backfill_job SET stop_requested=1,updated_at=? WHERE job_id=?").run(iso(now),id);return historicalJob(db,id)!;}
export function recoverStaleHistoricalState(db:DatabaseSync,id:string,now:Date):HistoricalJob {const job=historicalJob(db,id);if(!job)throw new Error("HISTORICAL_JOB_NOT_FOUND");const lease=collectorLease(db,now);if(lease?.mode==="historical"&&lease.jobId===id&&lease.fresh)throw new Error("COLLECTOR_BUSY");if(lease?.mode==="historical"&&lease.jobId===id&&!lease.fresh)db.prepare("DELETE FROM collector_lease WHERE lease_name=?").run(LEASE_NAME);const at=iso(now);db.prepare("UPDATE historical_backfill_chunk SET status='failed',completed_at=?,error_category='stale',error_summary='Recovered stale running chunk' WHERE job_id=? AND status='running'").run(at,id);if(job.status==="running")db.prepare("UPDATE historical_backfill_job SET status='paused',updated_at=? WHERE job_id=?").run(at,id);return historicalJob(db,id)!;}
export function prepareHistoricalResume(db:DatabaseSync,id:string,now:Date):{job:HistoricalJob;chunk:HistoricalChunk|undefined} {let job=recoverStaleHistoricalState(db,id,now);if(job.status==="completed")throw new Error("ALREADY_COMPLETED");if(job.status==="cancelled"||job.status==="failed")throw new Error("HISTORICAL_JOB_NOT_RESUMABLE");db.prepare("UPDATE historical_backfill_job SET stop_requested=0,status='paused',started_at=COALESCE(started_at,?),updated_at=? WHERE job_id=?").run(iso(now),iso(now),id);job=historicalJob(db,id)!;return {job,chunk:nextHistoricalChunk(db,id)};}
export function historicalStatus(db:DatabaseSync,id:string,now:Date){const job=historicalJob(db,id);if(!job)return undefined;const chunks=db.prepare("SELECT * FROM historical_backfill_chunk WHERE job_id=? ORDER BY range_start DESC LIMIT 1").get(id);const work=db.prepare("SELECT status,count(*) count FROM collector_work_item GROUP BY status ORDER BY status").all();const span=millis(job.cutoffBoundary)-millis(job.startBoundary);const progress=job.successfulThrough?Math.max(0,Math.min(1,(millis(job.successfulThrough)-millis(job.startBoundary)+60_000)/span)):0;return {job,progressByTime:progress,lastChunk:chunks?rowChunk(chunks):null,lease:collectorLease(db,now)??null,work,apiCalls:0};}
