import test from "node:test";
import assert from "node:assert/strict";
import { openMarketDatabase, CURRENT_SCHEMA_VERSION } from "../storage/database.js";
import { acquireCollectorLease, collectorLease, completeHistoricalChunk, createHistoricalJob, historicalStatus, nextHistoricalChunk, prepareHistoricalResume, recoverStaleHistoricalState, releaseCollectorLease, requestHistoricalStop } from "./historical-state.js";
import { createRequestPacer } from "./request-pacer.js";

const now=new Date("2026-08-14T00:00:00Z");
function job(db:ReturnType<typeof openMarketDatabase>){return createHistoricalJob(db,{start:"2001-01-01",cutoff:"2001-01-03T23:59",now});}

test("Phase 3-G.1 migration creates durable historical operational tables",()=>{const db=openMarketDatabase(":memory:");assert.equal((db.prepare("PRAGMA user_version").get()as{user_version:number}).user_version,CURRENT_SCHEMA_VERSION);for(const table of ["historical_backfill_job","historical_backfill_chunk","collector_lease"])assert.ok(db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name=?").get(table));db.close();});
test("historical job validates immutable scope and one active job",()=>{const db=openMarketDatabase(":memory:");const created=job(db);assert.equal(created.successfulThrough,null);assert.equal(created.status,"planned");assert.throws(()=>createHistoricalJob(db,{start:"2001-01-01",cutoff:"2001-01-04",now}),/ACTIVE_HISTORICAL_JOB_EXISTS/u);assert.throws(()=>createHistoricalJob(openMarketDatabase(":memory:"),{start:"2000-12-31",cutoff:"2001-01-02",now}),/LOWER_BOUND/u);assert.throws(()=>createHistoricalJob(openMarketDatabase(":memory:"),{start:"2001-01-02T00:00",cutoff:"2001-01-02T00:00",now}),/BEFORE_CUTOFF/u);db.close();});
test("chunks are lazy, unique, advance only after success, and finish at cutoff",()=>{const db=openMarketDatabase(":memory:"),created=job(db);const first=nextHistoricalChunk(db,created.jobId)!;assert.equal(first.rangeStart,"2001-01-01T00:00:00");assert.equal(first.rangeEnd,"2001-01-01T23:59:00");assert.equal(nextHistoricalChunk(db,created.jobId)!.chunkId,first.chunkId);completeHistoricalChunk(db,first.chunkId,now);assert.equal(historicalStatus(db,created.jobId,now)!.job.successfulThrough,"2001-01-01T23:59:00");const second=nextHistoricalChunk(db,created.jobId)!;assert.equal(second.rangeStart,"2001-01-02T00:00:00");completeHistoricalChunk(db,second.chunkId,now);const third=nextHistoricalChunk(db,created.jobId)!;completeHistoricalChunk(db,third.chunkId,now);assert.equal(historicalStatus(db,created.jobId,now)!.job.status,"completed");assert.equal(nextHistoricalChunk(db,created.jobId),undefined);db.close();});
test("lease is exclusive, holder-bound, heartbeatable, and stale-recoverable",()=>{const db=openMarketDatabase(":memory:"),created=job(db);const held=acquireCollectorLease(db,{token:"a",mode:"historical",jobId:created.jobId,now,ttlMs:1});assert.equal(held.mode,"historical");assert.throws(()=>acquireCollectorLease(db,{token:"b",mode:"manual",now}),/COLLECTOR_BUSY/u);assert.throws(()=>releaseCollectorLease(db,"b"),/LEASE_NOT_HELD/u);const later=new Date(now.getTime()+2);assert.equal(collectorLease(db,later)!.fresh,false);recoverStaleHistoricalState(db,created.jobId,later);assert.equal(collectorLease(db,later),undefined);acquireCollectorLease(db,{token:"b",mode:"manual",now:later});releaseCollectorLease(db,"b");db.close();});
test("stop is durable and resume preparation preserves data while clearing stop",()=>{const db=openMarketDatabase(":memory:"),created=job(db);requestHistoricalStop(db,created.jobId,now);assert.equal(historicalStatus(db,created.jobId,now)!.job.stopRequested,true);const prepared=prepareHistoricalResume(db,created.jobId,now);assert.equal(prepared.job.stopRequested,false);assert.equal(prepared.job.successfulThrough,null);assert.equal(prepared.chunk!.status,"pending");db.close();});
test("stale running state becomes resumable without moving cursor",()=>{const db=openMarketDatabase(":memory:"),created=job(db),chunk=nextHistoricalChunk(db,created.jobId)!;db.prepare("UPDATE historical_backfill_job SET status='running' WHERE job_id=?").run(created.jobId);db.prepare("UPDATE historical_backfill_chunk SET status='running',attempts=1 WHERE chunk_id=?").run(chunk.chunkId);acquireCollectorLease(db,{token:"crashed",mode:"historical",jobId:created.jobId,now,ttlMs:1});const recovered=recoverStaleHistoricalState(db,created.jobId,new Date(now.getTime()+2));assert.equal(recovered.status,"paused");assert.equal(recovered.successfulThrough,null);assert.equal(historicalStatus(db,created.jobId,new Date(now.getTime()+2))!.lastChunk!.status,"failed");db.close();});
test("request pacer spaces attempt start times without real sleeping",async()=>{let clock=0;const waits:number[]=[];const pacer=createRequestPacer({minimumIntervalMs:500,now:()=>clock,sleep:async ms=>{waits.push(ms);clock+=ms;}});await pacer.beforeAttempt();clock+=100;await pacer.beforeAttempt();clock+=600;await pacer.beforeAttempt();assert.deepEqual(waits,[400]);});
test("request pacer applies a shared cooldown to every queued API attempt",async()=>{let clock=0;const starts:number[]=[];const pacer=createRequestPacer({minimumIntervalMs:2_000,now:()=>clock,sleep:async ms=>{clock+=ms;}});await pacer.beforeAttempt();starts.push(clock);pacer.imposeCooldown(60_000);const first=pacer.beforeAttempt().then(()=>starts.push(clock));const second=pacer.beforeAttempt().then(()=>starts.push(clock));await Promise.all([first,second]);assert.deepEqual(starts,[0,60_000,62_000]);});
