import { randomUUID } from "node:crypto";
import { existsSync } from "node:fs";
const pauseFile=process.env.MARKET_COLLECTOR_PAUSE_FILE;if(pauseFile)setInterval(()=>{if(existsSync(pauseFile))process.kill(process.pid,"SIGTERM");},250).unref();
import { openMarketDatabase,DEFAULT_MARKET_DB_PATH } from "../storage/database.js";
import { KonepsClient } from "../koneps/client.js";
import { loadKonepsConfig } from "../koneps/config.js";
import { createRequestPacer,INITIAL_RATE_LIMIT_DELAYS_MS } from "./request-pacer.js";
import { acquireCollectorLease,releaseCollectorLease } from "./historical-state.js";
import { ensureInitialJob,monthRange,nextInitialWork,type InitialTarget } from "./initial-state.js";
import { collectorFailureDiagnostic,INITIAL_MONTH_PAGE_ROWS,runManualCollection } from "./collector.js";

function value(argv:readonly string[],name:string){const i=argv.indexOf(name);return i<0?undefined:argv[i+1];}
function initialFailure(type:string,target:string,month:string,range:{start:string;end:string},failure:ReturnType<typeof collectorFailureDiagnostic>){return {type,target,month,range,httpStatus:failure.httpStatus,resultCode:failure.resultCode,resultMsg:failure.resultMsg,errorCategory:failure.category,operation:failure.operation};}
async function main(){const argv=process.argv.slice(2),db=openMarketDatabase(value(argv,"--database")??DEFAULT_MARKET_DB_PATH);const now=new Date();try{
  const targets=JSON.parse(value(argv,"--targets")??"[]") as InitialTarget[];const id=ensureInitialJob(db,targets,now);const token=randomUUID();acquireCollectorLease(db,{token,mode:"manual",now});
  let cancelled=false;const stop=()=>{cancelled=true;};process.once("SIGINT",stop);process.once("SIGTERM",stop);
  try{db.prepare("UPDATE initial_collection_job SET status='running',updated_at=? WHERE job_id=?").run(now.toISOString(),id);let rateLimitContext:{target:string;month:string}|undefined;const client=new KonepsClient({config:{...loadKonepsConfig(),maxRetries:2,baseBackoffMs:1000},pacer:createRequestPacer(),rateLimitRetryDelaysMs:INITIAL_RATE_LIMIT_DELAYS_MS,onRateLimitRetry:event=>{if(rateLimitContext)console.log(JSON.stringify({type:"RATE_LIMIT_RETRY",attempt:event.attempt,waitSeconds:event.waitSeconds,target:rateLimitContext.target,month:rateLimitContext.month,operation:event.operation}));}});let work:ReturnType<typeof nextInitialWork>;let rateLimitPartial=false;
    while(!cancelled&&(work=nextInitialWork(db,id))){const cutoff=(db.prepare("SELECT cutoff_at value FROM initial_collection_job WHERE job_id=?").get(id) as {value:string}).value;if(work.month>cutoff.slice(0,7)){db.prepare("UPDATE initial_collection_target SET status='completed',updated_at=? WHERE job_id=? AND dtil_prdct_clsfc_no=?").run(new Date().toISOString(),id,work.code);continue;}const range=monthRange(work.month,cutoff);db.prepare("UPDATE initial_collection_target SET status='running',updated_at=? WHERE job_id=? AND dtil_prdct_clsfc_no=?").run(new Date().toISOString(),id,work.code);
      rateLimitContext={target:work.code,month:work.month};
      const targetCode=work.code,targetMonth=work.month,startedAt=new Date().toISOString();
      db.prepare("INSERT INTO initial_month_probe(job_id,dtil_prdct_clsfc_no,month,range_start,range_end,total_count,status,probed_at) VALUES(?,?,?,?,?,0,'collecting',?) ON CONFLICT(job_id,dtil_prdct_clsfc_no,month) DO UPDATE SET range_start=excluded.range_start,range_end=excluded.range_end,status='collecting',probed_at=excluded.probed_at,completed_at=NULL").run(id,targetCode,targetMonth,range.start,range.end,startedAt);
      let runId:string|null=null;const plan={mode:"initial" as const,requestedRange:range,effectiveRange:range,checkpoint:null,overlapMinutes:0,chunkMinutes:0,chunkCount:1,operations:["getBidPblancListInfoThngPPSSrch","getBidPblancListInfoThngPurchsObjPrdct","getBidPblancListInfoThngBsisAmount"]};const result=await runManualCollection({database:db,client,plan,advanceIncrementalCheckpoint:false,detailedProductClassNo:targetCode,discoveryPageRows:INITIAL_MONTH_PAGE_ROWS,singleDiscoveryRange:true,isCancelled:()=>cancelled,onProgress:p=>console.log(JSON.stringify({progress:{target:targetCode,month:targetMonth,...p}}))});if(result.status!=="succeeded"){const type=`INITIAL_MONTH_${result.status.toUpperCase()}`;const failure=result.failure??collectorFailureDiagnostic(new Error(type),"unknown",range);const at=new Date().toISOString();db.prepare("UPDATE initial_month_probe SET status='partial',completed_at=NULL,last_run_id=?,total_count=? WHERE job_id=? AND dtil_prdct_clsfc_no=? AND month=?").run(result.runId,result.discoveryTotalCount,id,targetCode,targetMonth);db.prepare("UPDATE initial_collection_target SET status='paused',updated_at=? WHERE job_id=? AND dtil_prdct_clsfc_no=?").run(at,id,targetCode);if(failure.httpStatus===429){console.log(JSON.stringify(initialFailure("INITIAL_MONTH_PARTIAL",targetCode,targetMonth,range,failure)));rateLimitPartial=true;break;}console.log(JSON.stringify(initialFailure(type,targetCode,targetMonth,range,failure)));throw new Error(type);}runId=result.runId;db.prepare("UPDATE initial_month_probe SET total_count=? WHERE job_id=? AND dtil_prdct_clsfc_no=? AND month=?").run(result.discoveryTotalCount,id,targetCode,targetMonth);
      const at=new Date().toISOString();db.prepare("UPDATE initial_month_probe SET status='collected',completed_at=?,last_run_id=COALESCE(?,last_run_id) WHERE job_id=? AND dtil_prdct_clsfc_no=? AND month=?").run(at,runId,id,work.code,work.month);db.prepare("UPDATE initial_collection_target SET status='paused',successful_through_month=?,updated_at=? WHERE job_id=? AND dtil_prdct_clsfc_no=?").run(work.month,at,id,work.code);
    }const remaining=Number((db.prepare("SELECT count(*) n FROM initial_collection_target WHERE job_id=? AND status!='completed'").get(id) as {n:number}).n);db.prepare("UPDATE initial_collection_job SET status=?,updated_at=?,completed_at=? WHERE job_id=?").run(remaining||rateLimitPartial?"paused":"completed",new Date().toISOString(),remaining||rateLimitPartial?null:new Date().toISOString(),id);
  }finally{try{releaseCollectorLease(db,token);}catch{}}
}finally{db.close();}}
main().catch(error=>{console.error(error instanceof Error?error.message:"Initial collection failed");process.exitCode=1;});
