import type { DatabaseSync, SQLInputValue } from "node:sqlite";

type DataRow=Record<string,SQLInputValue>&{id:SQLInputValue;date:SQLInputValue;title:SQLInputValue;demand:SQLInputValue;class_no:SQLInputValue;class_name:SQLInputValue;bid_id:SQLInputValue;winner_name:SQLInputValue;successful_bid_amount:SQLInputValue;successful_bid_rate:SQLInputValue;decision_contract_no:SQLInputValue;contract_amount:SQLInputValue};
type IdRow={id:SQLInputValue};
const one=(db:DatabaseSync,sql:string,...args:SQLInputValue[])=>db.prepare(sql).get(...args) as IdRow|undefined;
export function rebuildProcurementGroups(db:DatabaseSync,rebuiltAt=new Date().toISOString()){
 db.exec("BEGIN IMMEDIATE");
 try{
  db.exec("DELETE FROM procurement_relation;DELETE FROM procurement_group_member;DELETE FROM procurement_group");
  const addGroup=db.prepare(`INSERT INTO procurement_group(representative_date,representative_title,demand_institution_name,detailed_product_class_no,detailed_product_class_name,item_category,representative_winner_name,representative_award_amount,representative_award_rate,representative_contract_name,representative_contract_amount,has_bid,has_award,has_contract,bid_count,award_count,contract_count,match_status,rebuilt_at)VALUES(?,?,?,?,?,'unknown',NULL,NULL,NULL,NULL,NULL,?,?,?, ?,?,?,?,?)`);
  const addMember=db.prepare("INSERT INTO procurement_group_member VALUES(?,?,?,?,?)");
  const addRelation=db.prepare("INSERT OR IGNORE INTO procurement_relation(from_type,from_id,to_type,to_id,relation_type,match_method,evidence_json,rebuilt_at)VALUES(?,?,?,?,?,?,?,?)");
  const bids=db.prepare("SELECT bid_notice_id id,notice_posted_local date,bid_ntce_name title,demand_institution_name demand,detailed_product_class_no class_no,detailed_product_class_name class_name FROM bid_notice ORDER BY bid_notice_id").all() as DataRow[];
  for(const b of bids){const result=addGroup.run(b.date,b.title,b.demand,b.class_no,b.class_name,1,0,0,1,0,0,"UNLINKED",rebuiltAt);addMember.run(Number(result.lastInsertRowid),"BID",b.id,"PRIMARY","UNLINKED");}
  const awards=db.prepare("SELECT award_result_id id,bid_notice_id bid_id,real_opening_local date,bid_ntce_name title,demand_institution_name demand,target_detailed_product_class_no class_no,winner_name,successful_bid_amount,successful_bid_rate FROM award_result ORDER BY award_result_id").all() as DataRow[];
  for(const a of awards){let group:IdRow|undefined,method="UNLINKED";if(a.bid_id!=null){group=one(db,"SELECT procurement_group_id id FROM procurement_group_member WHERE source_type='BID' AND source_id=?",a.bid_id);method=one(db,"SELECT 1 ok FROM bid_award_link WHERE bid_notice_id=? AND award_result_id=? AND match_status IN ('official_matched','manual_verified')",a.bid_id,a.id)?"EXACT":"STRONG";}if(!group){const r=addGroup.run(a.date,a.title,a.demand,a.class_no,null,0,1,0,0,1,0,"UNLINKED",rebuiltAt);group={id:Number(r.lastInsertRowid)};}addMember.run(group.id,"AWARD",a.id,"RESULT",method);if(method!=="UNLINKED")addRelation.run("BID",a.bid_id,"AWARD",a.id,"BID_AWARD",method,JSON.stringify({basis:method==="EXACT"?"official_integrated_api":"bid_notice_id"}),rebuiltAt);}
  const contracts=db.prepare("SELECT contract_result_id id,contract_date date,contract_name title,demand_institution_name demand,target_detailed_product_class_no class_no,decision_contract_no,contract_amount FROM contract_result ORDER BY contract_result_id").all() as DataRow[];
  for(const c of contracts){const links=db.prepare("SELECT DISTINCT bid_notice_id bid_id FROM bid_contract_link WHERE contract_result_id=? AND match_status IN ('official_matched','manual_verified') ORDER BY bid_notice_id").all(c.id) as DataRow[];let group=links.length===1?one(db,"SELECT procurement_group_id id FROM procurement_group_member WHERE source_type='BID' AND source_id=?",links[0]!.bid_id):undefined,method=group?"EXACT":"UNLINKED";if(!group){const r=addGroup.run(c.date,c.title,c.demand,c.class_no,null,0,0,1,0,0,1,"UNLINKED",rebuiltAt);group={id:Number(r.lastInsertRowid)};}addMember.run(group.id,"CONTRACT",c.id,"RESULT",method);if(method==="EXACT")addRelation.run("BID",links[0]!.bid_id,"CONTRACT",c.id,"BID_CONTRACT","EXACT",JSON.stringify({basis:"official_integrated_api"}),rebuiltAt);}
  db.exec(`UPDATE procurement_group SET
   bid_count=(SELECT count(*) FROM procurement_group_member m WHERE m.procurement_group_id=procurement_group.procurement_group_id AND source_type='BID'),
   award_count=(SELECT count(*) FROM procurement_group_member m WHERE m.procurement_group_id=procurement_group.procurement_group_id AND source_type='AWARD'),
   contract_count=(SELECT count(*) FROM procurement_group_member m WHERE m.procurement_group_id=procurement_group.procurement_group_id AND source_type='CONTRACT');
   UPDATE procurement_group SET has_bid=bid_count>0,has_award=award_count>0,has_contract=contract_count>0,
   match_status=CASE WHEN EXISTS(SELECT 1 FROM procurement_group_member m WHERE m.procurement_group_id=procurement_group.procurement_group_id AND m.match_method='EXACT') THEN 'EXACT' WHEN EXISTS(SELECT 1 FROM procurement_group_member m WHERE m.procurement_group_id=procurement_group.procurement_group_id AND m.match_method='STRONG') THEN 'STRONG' ELSE 'UNLINKED' END,
   representative_winner_name=(SELECT winner_name FROM award_result a JOIN procurement_group_member m ON m.source_type='AWARD' AND m.source_id=a.award_result_id WHERE m.procurement_group_id=procurement_group.procurement_group_id ORDER BY a.real_opening_local DESC,a.award_result_id DESC LIMIT 1),
   representative_award_amount=(SELECT successful_bid_amount FROM award_result a JOIN procurement_group_member m ON m.source_type='AWARD' AND m.source_id=a.award_result_id WHERE m.procurement_group_id=procurement_group.procurement_group_id ORDER BY a.real_opening_local DESC,a.award_result_id DESC LIMIT 1),
   representative_award_rate=(SELECT successful_bid_rate FROM award_result a JOIN procurement_group_member m ON m.source_type='AWARD' AND m.source_id=a.award_result_id WHERE m.procurement_group_id=procurement_group.procurement_group_id ORDER BY a.real_opening_local DESC,a.award_result_id DESC LIMIT 1),
   representative_contract_name=(SELECT contract_name FROM contract_result c JOIN procurement_group_member m ON m.source_type='CONTRACT' AND m.source_id=c.contract_result_id WHERE m.procurement_group_id=procurement_group.procurement_group_id ORDER BY c.contract_date DESC,c.contract_result_id DESC LIMIT 1),
   representative_contract_amount=(SELECT contract_amount FROM contract_result c JOIN procurement_group_member m ON m.source_type='CONTRACT' AND m.source_id=c.contract_result_id WHERE m.procurement_group_id=procurement_group.procurement_group_id ORDER BY c.contract_date DESC,c.contract_result_id DESC LIMIT 1);`);
  db.exec(`UPDATE procurement_group SET item_category=COALESCE((SELECT CASE WHEN count(DISTINCT d.category)=1 THEN min(d.category) WHEN count(DISTINCT d.category)>1 THEN 'mixed' END FROM procurement_group_member m LEFT JOIN award_result a ON m.source_type='AWARD' AND a.award_result_id=m.source_id LEFT JOIN contract_result c ON m.source_type='CONTRACT' AND c.contract_result_id=m.source_id LEFT JOIN bid_notice b ON m.source_type='BID' AND b.bid_notice_id=m.source_id JOIN detailed_product_category d ON d.detailed_product_class_no=COALESCE(a.target_detailed_product_class_no,c.target_detailed_product_class_no,b.detailed_product_class_no) AND d.category IS NOT NULL WHERE m.procurement_group_id=procurement_group.procurement_group_id),'unknown')`);
  db.exec("COMMIT");return {groups:Number((db.prepare('SELECT count(*) n FROM procurement_group').get() as {n:number}).n),members:Number((db.prepare('SELECT count(*) n FROM procurement_group_member').get() as {n:number}).n)};
 }catch(error){db.exec("ROLLBACK");throw error;}
}
