import "./styles.css";
import { invoke } from "@tauri-apps/api/core";
import { listen } from "@tauri-apps/api/event";
import { getCurrentWindow } from "@tauri-apps/api/window";

type View="collector"|"search"|"dash"|"analysis"; type Row=Record<string,unknown>;
type CollectionFlow="bid"|"award"|"contract";
type CollectorTarget={dtilPrdctClsfcNo:string;dtilPrdctClsfcNoNm:string;useYn:string};
type TargetSearchResponse={ok:boolean;kind?:"name"|"exact"|"range";totalCount?:number;candidates?:CollectorTarget[];error?:string;resultCode?:string;resultMsg?:string};
type ApiKeyStatus={stored:boolean;source:"environment"|"development"|"wcm"|"none";credentialName:string};
const app=document.querySelector<HTMLDivElement>("#app")!; let view:View="dash", rows:Row[]=[], selected:Row|undefined, summary:Row={}, status:Row={}, logs:string[]=[];
let targetQuery="",targetCandidates:CollectorTarget[]=[],collectorTargets:CollectorTarget[]=[],targetSearching=false,targetError="";
let activeCollectionFlow:CollectionFlow|undefined;
let copyLogState:"idle"|"copied"|"error"="idle",copyLogTimer:number|undefined;
let apiKeyStatus:ApiKeyStatus={stored:false,source:"none",credentialName:"MonaRadar/Market/KONEPS"},apiKeyMessage="",apiKeyBusy=false;
const esc=(v:unknown)=>String(v??"").replace(/[&<>'"]/g,x=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[x]!)); const money=(x:unknown)=>x==null?"—":Number(x).toLocaleString("ko-KR")+"원";
function chrome(){if(!("__TAURI_INTERNALS__" in window))return;const w=getCurrentWindow();document.querySelector("#window-minimize")?.addEventListener("click",()=>void w.minimize());document.querySelector("#window-maximize")?.addEventListener("click",()=>void w.toggleMaximize());document.querySelector("#window-close")?.addEventListener("click",()=>void w.close());}
const nav=()=>`<aside><div class="brand"><span>MR</span><div><b>MONA RADAR</b><small>Market</small></div></div><nav>${(["dash","search","analysis","collector"] as View[]).map(v=>`<button data-view="${v}" class="${view===v?"active":""}">${v.charAt(0).toUpperCase()+v.slice(1)}</button>`).join("")}</nav><footer>LOCAL-FIRST<br><span>KONEPS market intelligence</span></footer></aside>`;
const dash=()=>`<section class="page"><header><p class="eyebrow">LOCAL MARKET INTELLIGENCE</p><h2>Dash</h2><p>로컬 SQLite에 저장된 실제 나라장터 수집 현황입니다.</p></header><div class="status-grid"><article><span>공고</span><strong>${Number(summary.notices??0).toLocaleString()}</strong><small>정규화된 bid_notice</small></article><article><span>구매대상물품</span><strong>${Number(summary.items??0).toLocaleString()}</strong><small>bid_item</small></article><article><span>기초금액</span><strong>${Number(summary.basisAmounts??0).toLocaleString()}</strong><small>bid_basis_amount</small></article><article><span>Checkpoint</span><strong>${esc(summary.checkpoint??"—")}</strong><small>마지막 완전 처리 범위</small></article></div><div class="log"><div class="log-head"><h3>최근 수집 실행</h3><span>SQLite evidence</span></div>${((summary.recentRuns as Row[]??[]).map(r=>`<div class="run"><b>${esc(r.status)}</b><span>${esc(r.startedAt)}</span><span>+${esc(r.inserted)} / △${esc(r.updated)} / =${esc(r.unchanged)}</span></div>`).join("")||'<div class="empty">수집 실행 이력이 없습니다.</div>')}</div></section>`;
const search=()=>`<section class="page"><header><p class="eyebrow">BID NOTICE INDEX</p><h2>Search</h2><p>공고명·공고기관·수요기관으로 로컬 데이터를 검색합니다.</p></header><div class="searchbox"><input id="query" placeholder="공고명 또는 기관명"><button id="search-go" class="primary">검색</button></div><div class="table"><div class="tr th"><span>공고</span><span>기관</span><span>게시 / 마감</span><span>추정가격</span></div>${rows.map((r,i)=>`<button class="tr" data-row="${i}"><span><b>${esc(r.name)}</b><small>${esc(r.bidNo)}-${esc(r.bidOrd)}</small></span><span>${esc(r.institution)}</span><span>${esc(r.postedAt)}<small>${esc(r.closeAt)}</small></span><span>${money(r.estimatedPrice)}</span></button>`).join("")||'<div class="empty">검색 결과가 없습니다. 수집 후 다시 검색하세요.</div>'}</div>${selected?detail():""}</section>`;
const detail=()=>`<article class="detail"><button id="detail-close">닫기</button><h3>${esc(selected?.name)}</h3><p>${esc(selected?.institution)} · ${esc(selected?.demandInstitution)}</p><div id="detail-body">세부 정보를 불러오는 중입니다.</div></article>`;
const analysis=()=>`<section class="page"><header><p class="eyebrow">EVIDENCE-BASED ANALYSIS</p><h2>Analysis</h2><p>현재 로컬 데이터의 가격·공고 분포를 바로 확인합니다.</p></header><div class="status-grid"><article><span>최근 공고 기준</span><strong>${esc(summary.latestNotice??"—")}</strong><small>notice_posted_local</small></article><article><span>정규화 원본</span><strong>${Number(summary.notices??0)+Number(summary.items??0)+Number(summary.basisAmounts??0)}</strong><small>공고·물품·금액 레코드</small></article></div><div class="empty">상세 분석은 Search 결과와 수집 evidence를 바탕으로 확장됩니다.</div></section>`;
const runningFlowClass=(flow:CollectionFlow)=>status.running&&activeCollectionFlow===flow?" is-running":"";
const resumable=(job:unknown)=>job!==null&&typeof job==="object"&&["planned","running","paused"].includes(String((job as Row).status??""));
function collectorButtons(flow:CollectionFlow,available:boolean,canResume:boolean){const runningHere=status.running&&activeCollectionFlow===flow;const startDisabled=status.running||!available;return `<div class="collector-form"><button id="${flow}-initial" class="primary" ${startDisabled?"disabled":""}>최초수집</button><button id="${flow}-incremental" ${startDisabled?"disabled":""}>최근변경수집</button><button id="${flow}-pause" ${runningHere?"":"disabled"}>일시정지</button><button id="${flow}-resume" ${status.running||!available||!canResume?"disabled":""}>재개</button></div>`;}
const collector=()=>`<section class="page"><header><p class="eyebrow">KONEPS API COLLECTOR</p><h2>Collector</h2><p>API 키는 앱 화면·로그·SQLite에 저장하지 않으며 collector 실행 환경에서만 사용합니다.</p></header><div class="status-grid"><article><span>저장소</span><strong>${status.ready?"READY":"EMPTY"}</strong><small>${esc(status.checkpoint??"초기 수집 필요")}</small></article><article><span>공통 실행 상태</span><strong>${status.running?"RUNNING":"IDLE"}</strong><small>한 번에 하나의 수집만 실행</small></article></div><div class="workspace target-selector"><h3>수집 Target</h3><p class="hint">세부품명, 10자리 세부품명번호 또는 8자리 상위번호로 검색합니다.</p><div class="target-search"><input id="target-query" value="${esc(targetQuery)}" placeholder="예: 전진공동펌프 / 4015155301 / 40151553"><button id="target-search" class="primary" ${targetSearching||status.running?"disabled":""}>${targetSearching?"검색 중…":"후보 검색"}</button></div>${targetError?`<div class="target-error">${esc(targetError)}</div>`:""}${targetCandidates.length?`<div class="target-results"><div class="target-row target-head"><span>세부품명</span><span>10자리 세부품명번호</span><span>사용여부</span><span></span></div>${targetCandidates.map((candidate,index)=>{const added=collectorTargets.some(target=>target.dtilPrdctClsfcNo===candidate.dtilPrdctClsfcNo);return `<div class="target-row"><span>${esc(candidate.dtilPrdctClsfcNoNm)}</span><code>${esc(candidate.dtilPrdctClsfcNo)}</code><span>${esc(candidate.useYn||"—")}</span><button data-add-target="${index}" ${added||status.running?"disabled":""}>${added?"선택됨":"추가"}</button></div>`}).join("")}</div>`:""}<h4>선택 Target <small>${collectorTargets.length}개</small></h4><div class="selected-targets">${collectorTargets.map((target,index)=>`<div class="selected-target"><span><b>${esc(target.dtilPrdctClsfcNoNm)}</b><code>${esc(target.dtilPrdctClsfcNo)}</code></span><button data-remove-target="${index}" ${status.running?"disabled":""} aria-label="${esc(target.dtilPrdctClsfcNoNm)} 삭제">삭제</button></div>`).join("")||'<p class="hint">선택된 Target이 없습니다.</p>'}</div></div><div class="collection-flows"><div class="workspace collection-flow${runningFlowClass("bid")}"><h3>입찰 수집</h3>${collectorButtons("bid",true,resumable(status.job))}<p class="hint">${esc((status.job as Row|undefined)?.through??"작업 없음")}</p></div><div class="workspace collection-flow${runningFlowClass("award")}"><h3>낙찰 수집</h3>${collectorButtons("award",true,resumable(status.awardJob))}<p class="hint">${esc((status.awardJob as Row|undefined)?.through??"작업 없음")}</p></div><div class="workspace collection-flow disabled-flow${runningFlowClass("contract")}"><h3>계약 수집</h3>${collectorButtons("contract",false,false)}<p class="hint">수집 backend 준비 중</p></div></div><div class="log"><div class="log-head"><h3>작업 로그</h3><span>redacted runtime events</span></div><pre>${esc(logs.join("\n")||"수집기가 대기 중입니다.")}</pre></div></section>`;
function render(){app.innerHTML=`${nav()}<main>${view==="dash"?dash():view==="search"?search():view==="analysis"?analysis():collector()}</main>`;document.querySelectorAll<HTMLButtonElement>("[data-view]").forEach(b=>b.onclick=()=>{view=b.dataset.view as View;render();void refresh();});document.querySelector("#search-go")?.addEventListener("click",()=>void doSearch());document.querySelectorAll<HTMLButtonElement>("[data-row]").forEach(b=>b.onclick=()=>{selected=rows[Number(b.dataset.row)];render();void loadDetail();});document.querySelector("#detail-close")?.addEventListener("click",()=>{selected=undefined;render();});document.querySelector("#target-search")?.addEventListener("click",()=>void searchTargets());document.querySelector<HTMLInputElement>("#target-query")?.addEventListener("keydown",event=>{if(event.key==="Enter")void searchTargets();});document.querySelectorAll<HTMLButtonElement>("[data-add-target]").forEach(button=>button.onclick=()=>addTarget(Number(button.dataset.addTarget)));document.querySelectorAll<HTMLButtonElement>("[data-remove-target]").forEach(button=>button.onclick=()=>removeTarget(Number(button.dataset.removeTarget)));document.querySelector("#bid-initial")?.addEventListener("click",()=>void start("initial"));document.querySelector("#bid-incremental")?.addEventListener("click",()=>void start("incremental"));document.querySelector("#bid-resume")?.addEventListener("click",()=>void start("historical"));document.querySelector("#award-initial")?.addEventListener("click",()=>void start("award"));document.querySelector("#award-incremental")?.addEventListener("click",()=>void start("award"));document.querySelector("#award-resume")?.addEventListener("click",()=>void start("award",true));document.querySelector("#bid-pause")?.addEventListener("click",()=>void pause());document.querySelector("#award-pause")?.addEventListener("click",()=>void pause());chrome();}
async function refresh(){try{summary=await invoke<Row>("dashboard_summary");}catch{summary={};}status=await invoke<Row>("collector_status");if(!status.running)activeCollectionFlow=undefined;if(view==="dash"||view==="analysis"||view==="collector")render();}
async function doSearch(){const q=(document.querySelector<HTMLInputElement>("#query")?.value??"");try{rows=(await invoke<{rows:Row[]}>("search_notices",{query:q})).rows;}catch(e){logs.unshift(String(e));}selected=undefined;render();}
async function loadDetail(){if(!selected)return;try{const d=await invoke<Row>("notice_detail",{bidNo:selected.bidNo,bidOrd:selected.bidOrd});const n=d.notice as Row, items=d.items as Row[], b=d.basis as Row|undefined;const host=document.querySelector("#detail-body");if(host)host.innerHTML=`<dl><dt>마감</dt><dd>${esc(n.bidClose)}</dd><dt>추정가격</dt><dd>${money(n.estimatedPrice)}</dd><dt>기초금액</dt><dd>${money(b?.basisAmount)}</dd></dl><h4>구매대상물품</h4>${items.map(i=>`<p>${esc(i.detailClassName||i.className)} · ${esc(i.quantity)} ${esc(i.unit)}</p>`).join("")||"등록된 물품이 없습니다."}`;}catch(e){const h=document.querySelector("#detail-body");if(h)h.textContent=String(e);}}
async function searchTargets(){targetQuery=document.querySelector<HTMLInputElement>("#target-query")?.value.trim()??"";targetSearching=true;targetError="";render();try{const result=await invoke<TargetSearchResponse>("search_collection_targets",{query:targetQuery});if(!result.ok){targetCandidates=[];targetError=[result.error,result.resultCode&&`resultCode=${result.resultCode}`,result.resultMsg].filter(Boolean).join(" · ");}else{targetCandidates=result.candidates??[];if(!targetCandidates.length)targetError="검색된 10자리 세부품명 후보가 없습니다.";}}catch(error){targetCandidates=[];targetError=String(error);}finally{targetSearching=false;render();}}
function addTarget(index:number){const candidate=targetCandidates[index];if(!candidate||collectorTargets.some(target=>target.dtilPrdctClsfcNo===candidate.dtilPrdctClsfcNo))return;collectorTargets=[...collectorTargets,candidate];render();}
function removeTarget(index:number){collectorTargets=collectorTargets.filter((_,candidateIndex)=>candidateIndex!==index);render();}
function mountLogCopy(){if(view!=="collector")return;const head=document.querySelector<HTMLElement>(".log .log-head");if(!head||head.querySelector("#copy-all-logs"))return;const group=document.createElement("div"),label=head.querySelector("span"),button=document.createElement("button");button.id="copy-all-logs";button.textContent=copyLogState==="copied"?"복사됨":copyLogState==="error"?"복사 실패":"전체 복사";if(label)group.append(label);group.append(button);head.append(group);button.addEventListener("click",()=>void copyAllLogs());}
async function copyAllLogs(){if(copyLogTimer!==undefined)window.clearTimeout(copyLogTimer);try{await navigator.clipboard.writeText(logs.join("\n"));copyLogState="copied";}catch{copyLogState="error";}mountLogCopyState();copyLogTimer=window.setTimeout(()=>{copyLogState="idle";mountLogCopyState();},1600);}
function mountLogCopyState(){const button=document.querySelector<HTMLButtonElement>("#copy-all-logs");if(button)button.textContent=copyLogState==="copied"?"복사됨":copyLogState==="error"?"복사 실패":"전체 복사";}
async function start(mode:string,resume=false){try{if(!resume&&(mode==="initial"||mode==="award")&&!collectorTargets.length)throw new Error("수집 Target을 하나 이상 선택하세요.");await invoke("start_collection",{mode,targets:resume?[]:mode==="initial"||mode==="award"?collectorTargets:[]});logs.unshift(`${mode} collector started`);activeCollectionFlow=mode==="award"?"award":"bid";status={...status,running:true};render();}catch(e){logs.unshift(`ERROR: ${String(e)}`);render();}}
async function pause(){try{await invoke("stop_collection");logs.unshift(`${activeCollectionFlow??"collector"} collector paused`);status={...status,running:false};activeCollectionFlow=undefined;await refresh();}catch(e){logs.unshift(`ERROR: ${String(e)}`);render();}}
function mountApiKeyPanel(){if(view!=="collector"||document.querySelector(".api-key-panel"))return;const header=document.querySelector("main .page header");if(!header)return;const source={environment:"실행환경",development:"개발 .env",wcm:"WCM",none:"없음"}[apiKeyStatus.source];const panel=document.createElement("div");panel.className="workspace api-key-panel";panel.innerHTML=`<div class="api-key-heading"><div><h3>Market API 키</h3><p class="hint">${apiKeyStatus.stored?"WCM 저장됨":"WCM에 저장되지 않음"} · 현재 사용: ${esc(source)}</p></div><span class="credential-state ${apiKeyStatus.stored?"saved":""}">${apiKeyStatus.stored?"SAVED":"NOT SAVED"}</span></div><div class="api-key-controls"><input id="api-key" type="password" autocomplete="new-password" placeholder="API 키 입력"><select id="api-key-mode" aria-label="API 키 모드"><option value="preserve">preserve</option><option value="encode">encode</option></select><button id="save-api-key" class="primary" ${apiKeyBusy?"disabled":""}>저장</button><button id="test-api-key" ${apiKeyBusy?"disabled":""}>연결 테스트</button></div>${apiKeyMessage?`<p class="api-key-message">${esc(apiKeyMessage)}</p>`:""}`;header.insertAdjacentElement("afterend",panel);panel.querySelector("#save-api-key")?.addEventListener("click",()=>void saveApiKey());panel.querySelector("#test-api-key")?.addEventListener("click",()=>void testApiKey());}
async function loadApiKeyStatus(){try{apiKeyStatus=await invoke<ApiKeyStatus>("api_key_status");}catch{}mountApiKeyPanel();}
async function saveApiKey(){const input=document.querySelector<HTMLInputElement>("#api-key"),mode=document.querySelector<HTMLSelectElement>("#api-key-mode")?.value??"preserve";if(!input?.value.trim()){apiKeyMessage="API 키를 입력하세요.";document.querySelector(".api-key-panel")?.remove();mountApiKeyPanel();return}apiKeyBusy=true;apiKeyMessage="";try{await invoke("save_api_key",{serviceKey:input.value,mode});input.value="";apiKeyMessage="Windows Credential Manager에 저장했습니다.";apiKeyStatus=await invoke<ApiKeyStatus>("api_key_status");}catch(error){apiKeyMessage=String(error);}finally{apiKeyBusy=false;document.querySelector(".api-key-panel")?.remove();mountApiKeyPanel();}}
async function testApiKey(){apiKeyBusy=true;apiKeyMessage="연결 확인 중…";document.querySelector(".api-key-panel")?.remove();mountApiKeyPanel();try{const result=await invoke<{ok:boolean;resultCode?:string}>("test_api_key");apiKeyMessage=result.ok&&result.resultCode==="00"?"연결 성공 (resultCode=00)":"연결에 실패했습니다.";}catch(error){apiKeyMessage=`연결 실패: ${String(error)}`;}finally{apiKeyBusy=false;document.querySelector(".api-key-panel")?.remove();mountApiKeyPanel();}}
new MutationObserver(()=>{mountApiKeyPanel();mountLogCopy();}).observe(app,{childList:true,subtree:true});
void listen<unknown>("collector-event",e=>{logs.unshift(JSON.stringify(e.payload));logs=logs.slice(0,100);if(view==="collector")render();void refresh();});render();void refresh();
void loadApiKeyStatus();
